apiVersion: v1
kind: Service
metadata:
  name: app-mysql-router
  namespace: doroob-production
spec:
  # clusterIP: 10.43.11.51
  selector:
    app: app-mysql-router
  type: ClusterIP
  ports:
  - name: readwrite
    port: 6446
    targetPort: 6446
    protocol: TCP
  - name: readonly
    port: 6447
    targetPort: 6447
    protocol: TCP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: app-mysql-router
  namespace: doroob-production
spec:
  selector:
    matchLabels:
      app: app-mysql-router
  serviceName: "app-mysql-router"
  replicas: 1
  template:
    metadata:
      labels:
        app: app-mysql-router # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      hostAliases:
      - ip: x.x.x.x
        hostnames:
          - "app-db1"
      - ip: y.y.y.y
        hostnames:
          - "app-db2"
      - ip: z.z.z.z
        hostnames:
          - "app-db3"
      containers:
      - name: app-mysql-router
        image: sitmenadev/mysql-router:1.0
        ports:
        - containerPort: 6446
          name: readwrite
        - containerPort: 6447
          name: readonly
        env:
          - name: CLUSTER_ADMIN
            value: "clusteradmin"
          - name: CLUSETR_PASSWORD
            value: "changeme"
          - name: CLUSTER_MASTER
            value: "app-db1"
          - name: ROUTER
            value: "app_router"
          - name: ROUTER_USER
            value: "root"
        volumeMounts:
          - mountPath: "/app_router"
            name: mysql-router-volume
            readOnly: false
      volumes:
      - name: mysql-router-volume
        persistentVolumeClaim:
          claimName: mysql-router-volume
